### ISSUE TITLE
看了前两题，发现示例代码有几个问题

### ISSUE THREAD

**Issue by starinsun** [sanyuan0704/leetcode-js#1]
### 反转列表的递归实现
pre和cur的值赋反了吧；内层reverse没有return
```js
let reverseList = (head) =>{
  let reverse = (pre, cur) => {
    if(!cur) return pre;
    // 保存 next 节点
    let next = cur.next;
    cur.next = pre;
    return reverse(cur, next);
  }
  return reverse(null,head);
}
```

### 区间反转的循环实现
前面声明的前节点名称为start，后面赋值成了front

**Comment by sanyuan0704** [comment]
提issue前建议你先跑一跑leetcode测试，地址我放到相应文章里面了。

**Comment by sanyuan0704** [comment]
两段程序都是没有任何问题的。

**Comment by starinsun** [comment]
三元哥你跑一下啊，第一题的递归是跑不通的
```js
let reverseList = (head) =>{
  let reverse = (pre, cur) => {
    if(!cur) return pre;
    // 保存 next 节点
    let next = cur.next;
    cur.next = pre;
    reverse(cur, next);
  }
  return reverse(head);
}
```
![image](https://user-images.githubusercontent.com/45473848/73619056-757dab00-4666-11ea-8fc6-c95e688abfb3.png)

第二题是可以AC，但是你代码前面声明了start后面没有使用，反而使用了没有声明的front

**Comment by sanyuan0704** [comment]
确实



---原始邮件---
发件人: "ESWang"<notifications@github.com&gt;
发送时间: 2020年2月3日(周一) 上午9:23
收件人: "sanyuan0704/leetcode-js"<leetcode-js@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"sanyuan0704"<494130947@qq.com&gt;;
主题: Re: [sanyuan0704/leetcode-js] 看了前两题，发现示例代码有几个问题 (#1)



三元哥你跑一下啊，第一题的递归是跑不通的
 let reverseList = (head) =&gt;{   let reverse = (pre, cur) =&gt; {     if(!cur) return pre;     // 保存 next 节点     let next = cur.next;     cur.next = pre;     reverse(cur, next);   }   return reverse(head); }
 

 
第二题是可以AC，但是你代码前面声明了start后面没有使用，反而使用了没有声明的front

**Comment by sanyuan0704** [comment]
改过来了



---原始邮件---
发件人: "ESWang"<notifications@github.com&gt;
发送时间: 2020年2月3日(周一) 上午9:23
收件人: "sanyuan0704/leetcode-js"<leetcode-js@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"sanyuan0704"<494130947@qq.com&gt;;
主题: Re: [sanyuan0704/leetcode-js] 看了前两题，发现示例代码有几个问题 (#1)



三元哥你跑一下啊，第一题的递归是跑不通的
 let reverseList = (head) =&gt;{   let reverse = (pre, cur) =&gt; {     if(!cur) return pre;     // 保存 next 节点     let next = cur.next;     cur.next = pre;     reverse(cur, next);   }   return reverse(head); }
 

 
第二题是可以AC，但是你代码前面声明了start后面没有使用，反而使用了没有声明的front
